server:
  port: 8130 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    keyId: LTAI5tAsCN1XBX2RijQjmRQX
    keySecret: aO1Dlz5ApzdGXBaF4qM23zraxkSFvI
    bucketName: srb-file-ywh-200921